# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entry_month', models.IntegerField()),
                ('entry_day', models.IntegerField()),
                ('entry_year', models.IntegerField()),
                ('entry_date', models.DateField()),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
