# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget_item',
            name='entry_day',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='budget_item',
            name='entry_month',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='budget_item',
            name='entry_year',
            field=models.IntegerField(default=1),
        ),
    ]
