# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-31 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_budget_item_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget_item',
            name='expend_category',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
